_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 22 #20 for default
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 250000
  IMG_PER_BATCH_LABEL_TRAIN: 4
  IMG_PER_BATCH_LABEL_COMPARE: 4
  IMG_PER_BATCH_UNLABEL: 4
  CHECKPOINT_PERIOD: 1000000
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
#  TRAIN_LABEL: ("cjk_train",) #("voc_2012_trainval","voc_2007_trainval")
#  COMPARE_LABEL: ("cjk_compare",)
#  TRAIN_UNLABEL: ("cjk_semi",)
#  TEST: ("cjk_semi",)
  TRAIN_LABEL: ("cityscapes",) #("voc_2012_trainval","voc_2007_trainval")
  COMPARE_LABEL: ("cityscapes_cyclegan",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0 #8000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.5
  SUP_LOSS_WEIGHT: 1.0
  DIS_LOSS_WEIGHT: 0.2
  # UNSUP_LOSS_WEIGHT: 0.0
  # SUP_LOSS_WEIGHT: 0.0
  # DIS_LOSS_WEIGHT: 0.0
  DIS_TYPE: "res4" #["concate","p2","multi"]

  # DCL_channels: "1425"
TEST:
  EVAL_PERIOD: 1000
#OUTPUT_DIR: ./city_output/totally_no_grl
# OUTPUT_DIR: ./city_output/drd_just_a_try_in_2023_8_9__city_dr_just_compare/
OUTPUT_DIR: ./city_output/DA_faster_rcnn/ # no dcl the last validation  _compare__nononono
# OUTPUT_DIR: .output/res101_cityscape/model_best.pth
# OUTPUT_DIR: ./city_output/experionment_DCL_4_0.02/
# OUTPUT_DIR: ./city_output/drd_no_sigmoid/
#OUTPUT_DIR: ./fusion/123



# 1 0.04 ：0.1433
