_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  #WEIGHTS: /configs/R-101.pkl
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (6000,)
  FACTOR_LIST: (1,1)
  MAX_ITER: 15000
  IMG_PER_BATCH_LABEL_TRAIN: 8
  IMG_PER_BATCH_LABEL_COMPARE: 8
  IMG_PER_BATCH_UNLABEL: 8
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.005
DATALOADER:
  SUP_PERCENT: 100.0
  NUM_WORKERS: 0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("sonar_train",) #("voc_2012_trainval","voc_2007_trainval")
  COMPARE_LABEL: ("sonar_compare",)
  TRAIN_UNLABEL: ("sonar_semi_VALID",)
  TEST: ("sonar_semi_TEST",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  COMPARE_THRESHOLD: 0.3
  TEACHER_UPDATE_ITER: 1
#  BURN_UP_STEP: 80000
  BURN_UP_STEP: 4000
  EMA_KEEP_RATE: 0.999
  UNSUP_LOSS_WEIGHT: 1.0 #1.0 for oral
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4" #["concate","p2","multi"]
  DIS_LOSS_WEIGHT: 0.05
  FUSION_IOU_THR: 0.65
  FUSION_BBOX_THRESHOLD: 0.8
  FUSION_WEIGHT: [ 2,1 ]
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: ./output/sonar_IDCC
