_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS_DS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS_DP: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  RPN:
    IN_FEATURES: [ "p2", "p3", "p4", "p5","p6" ]
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
#    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    LOSS: "FocalLoss" # variant: "CrossEntropy"
    NUM_CLASSES: 1
#    IN_FEATURES : [ "p3", "p4", "p5", "p6" ]
    IN_FEATURES : [ "p2", "p3", "p4", "p5" ]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (6000,)
  FACTOR_LIST: (1, 1)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL_TRAIN: 4
  IMG_PER_BATCH_LABEL_COMPARE: 4
  IMG_PER_BATCH_UNLABEL: 4
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("sonar_train",) #("voc_2012_trainval","voc_2007_trainval")
  COMPARE_LABEL: ("sonar_compare",)
#  TRAIN_UNLABEL: ("sonar_semi",)
#  TEST: ("sonar_semi",)
  TRAIN_UNLABEL: ("sonar_semi_VALID",)
  TEST: ("sonar_semi_TEST",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
#  COMBINATION_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.999
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  FUSION_IOU_THR: 0.6
  FUSION_BBOX_THRESHOLD: 0.8
  FUSION_WEIGHT: [1,1]
  DIS_TYPE: "p5" #["concate","p2","multi"]
  INITIAL_ITER: 28000
  UPDATE_ITER: 1
#  DISTEN: "p2"
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: ../update_4