_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 18000
  IMG_PER_BATCH_LABEL_TRAIN: 8
  IMG_PER_BATCH_LABEL_COMPARE: 8
  IMG_PER_BATCH_UNLABEL: 8
  CHECKPOINT_PERIOD: 2000
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes",) #("voc_2012_trainval","voc_2007_trainval")
  COMPARE_LABEL: ("cityscapes_cyclegan",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_LOSS_WEIGHT: 0.0
  DIS_TYPE: "res4" #["concate","p2","multi"]
#  DIS_LOSS_WEIGHT: 0.0
  FUSION_IOU_THR: 0.6
  FUSION_BBOX_THRESHOLD: 0.8
  FUSION_WEIGHT: [ 1,1 ]
  INITIAL_ITER: 18000
#  COMBIN_ITER: 13000
  UPDATE_ITER: 1

TEST:
  EVAL_PERIOD: 500
#OUTPUT_DIR: ./output/true_clipart_0.2_grl_0.9996_3unsup_1sup_10000_ini_0.02pseudo_compare
OUTPUT_DIR: ./res50/fusion1
DS_OUTPUT_DIR: ./res50/ds/
DP_OUTPUT_DIR: ./res50/dp/